---
all:
  children:
    main:
      hosts:
        pc:
        laptop:
    work:
      hosts:
        worklaptop:
    ubuntu:
      hosts:
        pc:
        laptop:
    servers:
      hosts:
        nas:

...
